-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 01:22:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema system_account
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema system_account
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `system_account` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `system_account` ;

-- -----------------------------------------------------
-- Table `system_account`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_account`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `system_account`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_account`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `roleID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `roleID` (`roleID` ASC) INVISIBLE,
  INDEX `id` (`id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`roleID`)
    REFERENCES `system_account`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `system_account`.`fired_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_account`.`fired_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login_user` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `system_account`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `system_account`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_account`.`profile` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fam` VARCHAR(45) NOT NULL,
  `otch` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `emailUser` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `system_account`.`salarytable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system_account`.`salarytable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `month` INT NOT NULL,
  `salary` DOUBLE NOT NULL,
  `tax` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  `award` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `login` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
